import type { TRLItem } from '../types/trl';

const mockTRL: TRLItem[] = [
  {
    id: 1,
    createdAt: "2025-08-03T14:45:00.000Z",
    research_id: "M0001",
    researchTitle: 'Smart Health Monitor',
    researchType: "TRL medicines vaccines stem cells",
    keyword: "AI, IoT, Health Tech",
    description: 'อุปกรณ์ติดตามสุขภาพที่สามารถวัดค่าทางชีวภาพแบบเรียลไทม์ เพื่อป้องกันโรคล่วงหน้า',
    stageOfDevelopment: 'ทดลอง ทดสอบ ความเป็นไปได้ทางตลาด หรือ พร้อมออกสู่ตลาด',
    currentChallenges: 'โรคเรื้อรังที่ตรวจพบช้า เช่น ความดัน เบาหวาน',
    targetUsers: 'ผู้ป่วยโรคเรื้อรัง, โรงพยาบาล, แพทย์เวชศาสตร์ครอบครัว',
    technologiesUsed: 'IoT, เซ็นเซอร์ชีวภาพ, AI สำหรับวิเคราะห์ข้อมูลสุขภาพ',
    marketComparison: 'ใช้งานง่ายกว่า และวิเคราะห์แม่นยำกว่าอุปกรณ์ทั่วไปในตลาด',
    ipStatus: 'ยังไม่จดสิทธิบัตร',
    marketing: 'ขายได้แน่นอน เพราะปัจจุบันคยหันมาใส่ใจสุขภาพมากขึ้น',
    support: 'ไม่มีแหล่งเงินทุนรายใหญ่ ผลักดันการพัฒนาจากทุนตนเอง',
    medicalBenefits: 'เพิ่มคุณภาพชีวิตผู้ป่วย ลดภาระงานแพทย์',
    commercializationChallenges: 'ต้นทุนสูง, ขาดพาร์ทเนอร์ทางอุตสาหกรรม',
    devSupportNeeded: 'ต้องการทุนสนับสนุน R&D และห้องแล็บสำหรับทดสอบต้นแบบ',
    marketSupportNeeded: 'ต้องการพาร์ทเนอร์สำหรับ pre-clinical trial และการตลาด',
    hasBusinessPartner: 'อยู่ระหว่างเจรจากับบริษัทผู้ผลิตอุปกรณ์การแพทย์',
    supportDevNeeded: ['ฝ่ายวิจัย', 'ศูนย์ขับเคลื่อนคุณค่าการบริการ (Center for Value Driven Care: VDC)'],
    supportMarketNeeded: ['การคุ้มครองทรัพย์สินทางปัญญา', 'หาผู้ร่วม/โรงงานผลิตและพัฒนานวัตกรรม', 'อื่น ๆ'],
    readyForShowcase: 'ยินดี',
    consent: 'รวบรวมเป็น innovation portfolio ของคณะ และนำไปทำ innovation catalog',
    trlRecommendation: {
      trlScore: null,
      status: false,
      reason: null,
      suggestion: null,
      sources: null,
      aiEstimate: null
      // trlScore: 2,
      // status: true,
      // reason: "เริ่มมีการพัฒนาเป็นต้นแบบ แต่ยังไม่พร้อมใช้งานจริง",
      // suggestion: "ทดสอบการใช้งานต้นแบบในสถานการณ์จริง และปรับปรุงระบบ",
      // sources: ["PubMed", "Google Scholar", "IEEE Xplore", "ScienceDirect", "ThaiJO"],
      // result: "result.pdf",
      // aiEstimate: null
    },
    isUrgent: false,
    urgentReason: "ต้องการอนุมัติเร่งด่วนเพื่อขอทุนวิจัยรอบพิเศษ",
    urgentFeedback: "ยังไม่เร่งด่วนมาก เนื่องจากปิดรับสมัครทุนแล้ว",
    createdBy: 'alice@professor.com',
  },
  {
    id: 2,
    createdAt: "2025-08-04T14:45:00.000Z",
    research_id: "S0001",
    researchTitle: 'Clinical Decision Support AI',
    researchType: "TRL software",
    description: 'ระบบ AI วิเคราะห์ข้อมูลเวชระเบียนอิเล็กทรอนิกส์ เพื่อช่วยแพทย์วินิจฉัยและเลือกแนวทางการรักษา',
    stageOfDevelopment: 'อยู่ในระยะต้นแบบ ทดสอบกับข้อมูลจำลองในโรงพยาบาล',
    currentChallenges: 'ความแม่นยำของโมเดล, ความเป็นส่วนตัวของข้อมูลผู้ป่วย',
    targetUsers: 'แพทย์ทั่วไป, โรงพยาบาล, คลินิกเวชกรรม',
    technologiesUsed: 'Natural Language Processing, Machine Learning, EHR Integration',
    marketComparison: 'มีอินเทอร์เฟซใช้ง่าย และเชื่อมต่อกับระบบเวชระเบียนที่ใช้อยู่แล้ว',
    ipStatus: 'มีการจดลิขสิทธิ์ซอฟต์แวร์แล้ว',
    marketing: 'อยู่ระหว่างการทดสอบตลาดในโรงพยาบาลนำร่อง',
    support: 'ได้รับทุนสนับสนุนจากโครงการ AI for Health',
    medicalBenefits: 'ลดอัตราการวินิจฉัยผิด เพิ่มประสิทธิภาพการรักษา',
    commercializationChallenges: 'ต้องผ่านการรับรองด้านความปลอดภัยของซอฟต์แวร์ทางการแพทย์',
    devSupportNeeded: 'ต้องการ data set ที่มีคุณภาพสูงจากโรงพยาบาลพันธมิตร',
    marketSupportNeeded: 'ต้องการหน่วยงานภาครัฐช่วยผลักดันการใช้งานจริง',
    hasBusinessPartner: 'มีความร่วมมือกับโรงพยาบาลเอกชน 2 แห่งในกรุงเทพฯ',
    supportDevNeeded: ['ฝ่ายวิจัย', 'ศูนย์ขับเคลื่อนคุณค่าการบริการ (Center for Value Driven Care: VDC)'],
    supportMarketNeeded: ['การคุ้มครองทรัพย์สินทางปัญญา', 'หาผู้ร่วม/โรงงานผลิตและพัฒนานวัตกรรม'],
    readyForShowcase: 'ยินดี',
    consent: 'ใช้ในรายงาน innovation portfolio ของโครงการ',
    trlRecommendation: {
      trlScore: null,
      status: false,
      reason: null,
      suggestion: null,
      sources: null,
      aiEstimate: null
      // trlScore: 3,
      // reason: "มีระบบต้นแบบและเริ่มทดสอบกับข้อมูลจริงบางส่วน",
      // suggestion: "นำระบบไปทดลองใช้ในสถานพยาบาลจริง และรับ feedback จากผู้ใช้",
      // sources: ["IEEE Xplore", "PubMed", "arXiv", "ThaiJO"]
    },
    isUrgent: true,
    urgentReason: "ต้องการการสนับสนุนเร่งด่วนเพื่อพัฒนาต้นแบบ",
    urgentFeedback: null,
    createdBy: 'alice@professor.com',
  },
  {
    id: 3,
    createdAt: "2025-08-05T14:45:00.000Z",
    research_id: "M0002",
    researchTitle: 'Stem Cell Wound Healing Gel',
    researchType: "TRL medicines vaccines stem cells",
    description: 'เจลบำบัดแผลเรื้อรังจากเซลล์ต้นกำเนิดที่กระตุ้นการสร้างเนื้อเยื่อใหม่',
    stageOfDevelopment: 'ผ่านการทดสอบในห้องแล็บและสัตว์ทดลอง',
    currentChallenges: 'ปัญหาการควบคุมคุณภาพของ stem cell ในระดับอุตสาหกรรม',
    targetUsers: 'โรงพยาบาล, คลินิกเฉพาะทาง, ผู้ป่วยเบาหวาน',
    technologiesUsed: 'Mesenchymal stem cell, hydrogel, tissue engineering',
    marketComparison: 'มีผลฟื้นฟูเร็วกว่าเจลทั่วไปและลดการเกิดแผลเป็น',
    ipStatus: 'จดสิทธิบัตรแล้วในประเทศ',
    marketing: 'อยู่ระหว่างการวางแผนเปิดตัวผลิตภัณฑ์ร่วมกับพาร์ทเนอร์',
    support: 'ได้รับการสนับสนุนจากทุนสกว.',
    medicalBenefits: 'ลดการตัดอวัยวะจากแผลเรื้อรัง',
    commercializationChallenges: 'ต้องผ่านการทดลองทางคลินิก',
    devSupportNeeded: 'ต้องการโรงงาน GMP และทีม QC',
    marketSupportNeeded: 'ต้องการที่ปรึกษาการนำผลิตภัณฑ์เข้าสู่ตลาดสากล',
    hasBusinessPartner: 'มีความร่วมมือกับบริษัทเครื่องมือแพทย์',
    supportDevNeeded: ['ฝ่ายวิจัย', 'ศูนย์ขับเคลื่อนคุณค่าการบริการ (Center for Value Driven Care: VDC)'],
    supportMarketNeeded: ['การคุ้มครองทรัพย์สินทางปัญญา', 'หาผู้ร่วม/โรงงานผลิตและพัฒนานวัตกรรม', 'อื่น ๆ'],
    readyForShowcase: 'ยินดี',
    consent: 'เผยแพร่ในรายงานความก้าวหน้าวิจัย',
    trlRecommendation: {
      trlScore: 4,
      status: true,
      reason: "มีผลการทดลองในสัตว์อย่างชัดเจน",
      suggestion: "เริ่มขั้นตอนจัดทำแผนการทดลองในมนุษย์",
      sources: ["Scopus", "PubMed"],
      result: "result.pdf",
      aiEstimate: null
    },
    isUrgent: false,
    urgentReason: null,
    urgentFeedback: null,
    createdBy: 'alice@professor.com',
  },
  {
    id: 4,
    createdAt: "2025-08-06T14:45:00.000Z",
    research_id: "M0003",
    researchTitle: 'AI Drug Repurposing System',
    researchType: "TRL medicines vaccines stem cells",
    description: 'ระบบ AI สำหรับค้นหาการใช้ยาเดิมกับโรคใหม่',
    stageOfDevelopment: 'ระยะต้นแบบใช้งานภายในแล็บ',
    currentChallenges: 'ฐานข้อมูลขนาดใหญ่และความถูกต้องของโมเดล',
    targetUsers: 'นักวิจัยยา, บริษัทเภสัชภัณฑ์',
    technologiesUsed: 'Machine learning, deep neural networks, bioinformatics',
    marketComparison: 'ประหยัดเวลาและต้นทุนเทียบกับวิธีเดิม',
    ipStatus: 'รอการประเมินด้านลิขสิทธิ์ซอฟต์แวร์',
    marketing: 'เน้นใช้ใน B2B และบริการวิจัยร่วม',
    support: 'ได้รับทุน seed fund จาก incubator',
    medicalBenefits: 'ช่วยค้นหาวิธีรักษาโรคหายากได้รวดเร็ว',
    commercializationChallenges: 'ยังไม่มี use case เชิงพาณิชย์',
    devSupportNeeded: 'ต้องการพาร์ทเนอร์ด้าน big pharma',
    marketSupportNeeded: 'การยอมรับในวงการแพทย์',
    hasBusinessPartner: 'ยังไม่มี',
    supportDevNeeded: ['ฝ่ายวิจัย', 'ศูนย์ขับเคลื่อนคุณค่าการบริการ (Center for Value Driven Care: VDC)'],
    supportMarketNeeded: ['การคุ้มครองทรัพย์สินทางปัญญา', 'หาผู้ร่วม/โรงงานผลิตและพัฒนานวัตกรรม', 'อื่น ๆ'],
    readyForShowcase: 'ไม่แน่ใจ',
    consent: 'ใช้สำหรับประเมินภายในเท่านั้น',
    trlRecommendation: {
      trlScore: 2,
      status: true,
      reason: "อยู่ในขั้นตอนทดสอบระบบ",
      suggestion: "สร้างโมเดลต้นแบบสำหรับโรคที่มีข้อมูลมาก เช่น เบาหวาน",
      sources: ["arXiv", "Google Scholar"],
      result: "result.pdf",
      aiEstimate: null
    },
    isUrgent: false,
    urgentReason: null,
    urgentFeedback: null,
    createdBy: 'alice@professor.com',
  },
  {
    id: 5,
    createdAt: "2025-08-07T14:45:00.000Z",
    research_id: "M0004",
    researchTitle: 'Oral Insulin Nanoformulation',
    researchType: "TRL medicines vaccines stem cells",
    description: 'นวัตกรรมอินซูลินชนิดรับประทานด้วยเทคโนโลยีนาโนเพื่อการดูดซึมสูงสุด',
    stageOfDevelopment: 'ผ่าน animal trial แล้ว',
    currentChallenges: 'การควบคุมเสถียรภาพของยาในกระเพาะอาหาร',
    targetUsers: 'ผู้ป่วยเบาหวาน, บริษัทผลิตยา',
    technologiesUsed: 'Nanoparticles, enteric coating, pharmacokinetics',
    marketComparison: 'สะดวกกว่าการฉีดและลดต้นทุนในระยะยาว',
    ipStatus: 'อยู่ระหว่างการจดในต่างประเทศ',
    marketing: 'สามารถสร้าง demand ได้หากผ่าน clinical trial',
    support: 'ได้รับทุนสนับสนุนจากองค์กรพัฒนาเภสัช',
    medicalBenefits: 'เพิ่ม compliance และลดภาระการรักษา',
    commercializationChallenges: 'ต้องผ่านการทดลองในคนหลายระยะ',
    devSupportNeeded: 'ต้องการ CMO สำหรับผลิต GMP',
    marketSupportNeeded: 'ต้องการบริษัทจัดจำหน่ายที่มีช่องทางทั่วประเทศ',
    hasBusinessPartner: 'มีข้อตกลงเบื้องต้นกับบริษัทยาในอินเดีย',
    supportDevNeeded: ['ฝ่ายวิจัย', 'ศูนย์ขับเคลื่อนคุณค่าการบริการ (Center for Value Driven Care: VDC)'],
    supportMarketNeeded: ['การคุ้มครองทรัพย์สินทางปัญญา', 'หาผู้ร่วม/โรงงานผลิตและพัฒนานวัตกรรม', 'อื่น ๆ'],
    readyForShowcase: 'ยินดี',
    consent: 'เพื่อใช้ในการส่งเสริมงานวิจัยระดับชาติ',
    trlRecommendation: {
      trlScore: 3,
      status: true,
      reason: "ผลเบื้องต้นดีในสัตว์",
      suggestion: "เตรียมเอกสารเพื่อยื่นขอ IRB และ trial",
      sources: ["PubMed", "ScienceDirect"],
      result: "result.pdf",
      aiEstimate: null
    },
    isUrgent: false,
    urgentReason: null,
    urgentFeedback: null,
    createdBy: 'alice@professor.com',
  },
  {
    id: 6,
    createdAt: "2025-08-08T14:45:00.000Z",
    research_id: "M0005",
    researchTitle: 'Cancer Immunotherapy by CAR-T',
    researchType: "TRL medicines vaccines stem cells",
    description: 'การรักษามะเร็งโดยการใช้เซลล์ภูมิคุ้มกันที่ดัดแปลงพันธุกรรม',
    stageOfDevelopment: 'เริ่มต้น clinical trial ระยะที่ 1',
    currentChallenges: 'ค่าใช้จ่ายสูงและข้อจำกัดทางเทคนิค',
    targetUsers: 'ผู้ป่วยมะเร็งระยะลุกลาม, โรงพยาบาลเฉพาะทาง',
    technologiesUsed: 'CAR-T cells, gene editing, immuno-oncology',
    marketComparison: 'มีผลการรักษาที่ลึกและยาวนานกว่าเคมีบำบัด',
    ipStatus: 'อยู่ในข้อตกลงร่วมกับหน่วยงานวิจัยสหรัฐ',
    marketing: 'ยังอยู่ในช่วง early adoption',
    support: 'ได้รับทุนจากโครงการวิจัยระดับนานาชาติ',
    medicalBenefits: 'รักษามะเร็งชนิดดื้อต่อการรักษาแบบเดิม',
    commercializationChallenges: 'กระบวนการผลิตซับซ้อน ต้องมี facility เฉพาะ',
    devSupportNeeded: 'ต้องการ GMP facility และบุคลากรเฉพาะทาง',
    marketSupportNeeded: 'ต้องการพันธมิตรธุรกิจในการขยายตลาดภูมิภาค',
    hasBusinessPartner: 'ร่วมมือกับศูนย์วิจัยมะเร็งในญี่ปุ่น',
    supportDevNeeded: ['ฝ่ายวิจัย', 'ศูนย์ขับเคลื่อนคุณค่าการบริการ (Center for Value Driven Care: VDC)'],
    supportMarketNeeded: ['การคุ้มครองทรัพย์สินทางปัญญา', 'หาผู้ร่วม/โรงงานผลิตและพัฒนานวัตกรรม', 'อื่น ๆ'],
    readyForShowcase: 'ยินดี',
    consent: 'ใช้ในฐานข้อมูลเท่านั้น ไม่เปิดเผยเชิงพาณิชย์',
    trlRecommendation: {
      trlScore: null,
      status: false,
      reason: null,
      suggestion: null,
      sources: null,
      aiEstimate: null
      // trlScore: 5,
      // reason: "เริ่ม clinical trial แล้ว",
      // suggestion: "ติดตามผลลัพธ์และปรับแผนตาม safety profile",
      // sources: ["Nature Medicine", "ClinicalTrials.gov"]
    },
    isUrgent: false,
    urgentReason: null,
    urgentFeedback: null,
    createdBy: 'alice@professor.com',
  },
  {
    id: 7,
    createdAt: "2025-08-09T14:45:00.000Z",
    research_id: "M0006",
    researchTitle: 'mRNA Vaccine Platform',
    researchType: "TRL medicines vaccines stem cells",
    description: 'แพลตฟอร์มสำหรับผลิตวัคซีน mRNA ที่สามารถดัดแปลงได้ตามเชื้อไวรัสที่กลายพันธุ์',
    stageOfDevelopment: 'ต้นแบบผ่านการทดลองในสัตว์',
    currentChallenges: 'ต้นทุนการผลิตสูงและความมั่นใจของผู้บริโภคต่อเทคโนโลยี mRNA',
    targetUsers: 'กระทรวงสาธารณสุข, โรงงานผลิตยา, บริษัทชีวเวชภัณฑ์',
    technologiesUsed: 'mRNA synthesis, lipid nanoparticles, cell culture',
    marketComparison: 'พัฒนาได้เร็วกว่าและมีความยืดหยุ่นสูงกว่าวัคซีนแบบเดิม',
    ipStatus: 'อยู่ระหว่างจดสิทธิบัตรระหว่างประเทศ',
    marketing: 'มีศักยภาพสูงโดยเฉพาะในยุค post-pandemic',
    support: 'ได้รับทุนวิจัยจากหน่วยงานรัฐ',
    medicalBenefits: 'ตอบสนองได้รวดเร็วต่อโรคอุบัติใหม่',
    commercializationChallenges: 'จำเป็นต้องผ่านขั้นตอน pre-clinical และ clinical trial',
    devSupportNeeded: 'ต้องการความร่วมมือกับบริษัทผลิตยา',
    marketSupportNeeded: 'สนับสนุนจากรัฐเพื่อกระจายวัคซีนในภาวะฉุกเฉิน',
    hasBusinessPartner: 'มีความร่วมมือกับสถาบันชีวเวชแห่งชาติ',
    supportDevNeeded: ['ฝ่ายวิจัย', 'ศูนย์ขับเคลื่อนคุณค่าการบริการ (Center for Value Driven Care: VDC)'],
    supportMarketNeeded: ['การคุ้มครองทรัพย์สินทางปัญญา', 'หาผู้ร่วม/โรงงานผลิตและพัฒนานวัตกรรม', 'อื่น ๆ'],
    readyForShowcase: 'ยินดี',
    consent: 'นำเสนอใน catalog และงาน innovation fair',
    trlRecommendation: {
      trlScore: 3,
      status: true,
      reason: "ผ่านการทดสอบในสัตว์แล้ว",
      suggestion: "เตรียมเอกสารเพื่อยื่นขออนุมัติการทดลองในมนุษย์",
      sources: ["Nature", "Cell", "ScienceDirect"],
      result: "result.pdf",
      aiEstimate: null
    },
    isUrgent: false,
    urgentReason: null,
    urgentFeedback: null,
    createdBy: 'alice@professor.com',
  }
];

export default mockTRL;
