@startuml
title Sequence Diagram: Admin Manages Appointments

actor Admin
participant "Frontend/UI" as UI
participant "Backend/API" as API
database "Database \n (Firebase)" as DB

Admin -> UI: Open 'Appointments Management' page
UI -> API: GET /trl/case/{case_id}
UI -> API: GET /trl/researcher/{researcher_id}
API -> DB: Fetch appointments list
DB --> API: Return appointments data
API --> UI: Return appointments list
UI -> Admin: Display appointments

@enduml
