@startuml
title Sequence Diagram: Admin Views All Research

actor Admin
participant "Frontend/UI" as UI
participant "Backend/API" as API
database "Database \n (Firebase)" as DB

Admin -> UI: Navigate to 'Admin Homepage' page
UI -> API: GET /trl/case/{id}
UI -> API: GET /trl/appointment/{id}
API -> DB: Fetch research data
DB --> API: Return research data
API --> UI: Return research data
UI --> Admin: Display research data

@enduml
