@startuml
title Sequence Diagram: Admin Add Appointments

actor Admin
participant "Frontend/UI" as UI
participant "Backend/API" as API
database "Database \n (Neon)" as DB

Admin -> UI: Open 'Appointments Management' page
UI -> API: POST /trl/appointment
API -> DB: Add appointments data
DB --> API: Success/Failure response
API --> UI: Return result (success/failure)
UI --> Admin: Show confirmation or error

@enduml
